[[connectors]]
id = "syslog_udp_sink"
type = "syslog"
allow_override = ["addr", "port", "protocol", "app_name" ]
[connectors.params]
addr = "127.0.0.1"
port = 1514
protocol = "udp"
app_name = "wp-engine"
strip_header = true
attach_meta_tags = true
tcp_recv_bytes = 10485760
