version = "2.0"

[sink_group]
name = "default"
batch_size = 128
batch_timeout_ms = 300

[[sink_group.sinks]]
connect = "file_proto_sink"
[sink_group.sinks.params]
file = "default.dat"
sync = false

[sink_group.sinks.expect]
ratio = 0.0
tol = 0.02
