version = "2.0"

[sink_group]
name = "miss"
batch_size = 1
batch_timeout_ms = 300

[[sink_group.sinks]]
connect = "file_json_sink"

[sink_group.sinks.params]
file = "miss.dat"

[sink_group.sinks.expect]
max = 0.1
min = 0.0
