version = "2.0"

[sink_group]
name = "monitor"
batch_size = 1
batch_timeout_ms = 300

[[sink_group.sinks]]
connect = "file_proto_sink"

[sink_group.sinks.params]
file = "monitor.dat"
sync = true

[sink_group.sinks.expect]
max = 1.0
